# Generated by Django 4.1 on 2022-08-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Category image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Img name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_welcome', to='main.category')),
            ],
            options={
                'verbose_name': 'Welcome',
                'verbose_name_plural': 'Welcome',
            },
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('about', models.TextField(verbose_name='About')),
                ('img', models.ImageField(upload_to='media', verbose_name='Img name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_work', to='main.category')),
            ],
            options={
                'verbose_name': 'OurWork',
                'verbose_name_plural': 'OurWorks',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Img name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ourteam', to='main.category')),
            ],
            options={
                'verbose_name': 'OurTeam',
                'verbose_name_plural': 'OurTeams',
            },
        ),
    ]
