# Generated by Django 4.1 on 2022-08-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_ourteam', to='main.category'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_work', to='main.category'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_welcome', to='main.category'),
        ),
    ]
